version: '3.8'

services:
  php:
    container_name: Ownsafe_PHP
    hostname: ownsafe_php
    restart: always
    build:
        context: ./docker/php
        dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: Ownsafe_NGINX
    hostname: ownsafe_nginx
    restart: always
    ports:
      - 81:80
    links:
      - php
    volumes:
      - ./docker/nginx-conf:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - php

  mariadb:
    image: mariadb:10.9
    container_name: Ownsafe_DB
    hostname: ownsafe_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ownsafe
      MARIADB_DATABASE: ownsafe
      MARIADB_USER: ownsafe
      MARIADB_PASSWORD: ownsafe
    command:
      - bash
      - -c
      - >
        mkdir -p ./docker/mysql;
    volumes:
      - ./docker/mysql:/var/lib/mysql

volumes:

  mysqldata:
