services:
  #app:
    #volumes:
      #- ./ownsafe:./
  
  php:
    container_name: Ownsafe_PHP
    hostname: ownsafe_php
    #restart: no
    #working_dicommand: ["bash", "-c", "git clone https://github.com/sepla/ownsafe.git ./"]r: ./
    command: ["bash", "-c", "git clone https://github.com/sepla/ownsafe.git ./"]
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./ownsafe:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: Ownsafe_NGINX
    hostname: ownsafe_nginx
    #restart: always
    ports:
      - 81:80
      - 444:443
    links:
      - 'php'
    volumes:
      - ./ownsafe/docker/nginx-conf:/etc/nginx/conf.d
      - ./ownsafe:/var/www/html
    networks:
      - net
    depends_on:
      - php

  mariadb:
    image: mariadb:10.8
    container_name: Ownsafe_DB
    hostname: ownsafe_db
    tty: true
    #restart: no
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ownsafe
      MARIADB_DATABASE: ownsafe
      MARIADB_USER: ownsafe
      MARIADB_PASSWORD: ownsafe
    #command:
    #  - bash
    #  - -c
    #  - >
    #  -  mkdir -p ./docker/mariadb-data;
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - net

  #phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: Ownsafe_PHPMYADMIN
  #   hostname: ownsafe_phpmyadmin
     #restart: no
   #  ports:
   #    - 82:8080
   #  environment:
   #     PMA_HOST: ownsafe_db
   #  networks:
   #    - net
   #  depends_on:
   #    - mariadb

networks:
  net:
    driver: bridge
    
volumes:
  mariadb-data:
