# Services
services:

  # PHP FPM Service
  php:
    container_name: Ownsafe_PHP
    hostname: ownsafe_php
    build:
      #context: https://github.com/sepla/ownsafe.gitsafe_PHP>Logs
      #dockerfile: ./docker/php/Dockerfile
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - '../www:/var/www/html'
      - './php/php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    depends_on:
      - mariadb
       #entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"] 
    #command: ['bash','-c','cp ./www.bak/index* ../www; pwd; tail -f ./index.html']
    tty: true 
     
  # Nginx Service
  nginx:
    container_name: Ownsafe_NGINX
    hostname: ownsafe_nginx
    build:
        #context: https://github.com/sepla/ownsafe.git
        #dockerfile: ./docker/nginx/Dockerfile
        context: .
        dockerfile: nginx/Dockerfile
    ports:
      - 1234:80
    links:
      - 'php'
    volumes:
      - '../www:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - 'php'
    #entrypoint: sh -c "/install-app.sh & exec /docker-entrypoint.sh nginx"
  
  # MariaDB Service
  mariadb:
    image: mariadb:10.9
    container_name: Ownsafe_DB
    hostname: ownsafe_db
    tty: true
    #restart: no
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ownsafe
      MARIADB_DATABASE: ownsafe
      MARIADB_USER: ownsafe
      MARIADB_PASSWORD: ownsafe
    volumes:
      - ./mariadb-data:/var/lib/mysql


# Volumes
volumes:
  mariadb-data:
